### ISSUE TITLE
[Suggestion] Add vertical glass panes.

### ISSUE THREAD

**Issue by MxOrbulent** [Wurst-Imperium/Mo-Glass#15]
Basically, slabs that are as thin as glasspanes. Stained versions too. They should be placeable as slabs are (either top or bottom).

**Comment by SpiderKolo** [comment]
I think you meant Horizontal?
Vertical are the ones in the game - going from top to bottom. That's how Vanilla Panes are placed.
Horizontal is what you meant - going from side to side. That's how Slabs are placed.

Though Panes on Edges of blocks would be cool, I remember seeing mod like that somewhere already.
I can however understand why you would want it in this mod - there is this working transparency which could make this look better.

That all being said - that would be a lot of work for... well, 17 new blocks, but each needing to be accounted for for transparency calculations...

Unless Vanilla Panes are not included in this calculation yet, in which case either the new panes would not have to OR both Vanilla and the new Horizontal Panes would now had to be accounted for.

Horizontal ones would also be accounted similarly to slabs - as you mentioned they would be placed as such MEANING there would be three states for those Horizontal panes alone.
And if we go with an approach where we put Panes on Edges/Acting as a thin walls INSTEAD of thin slabs - that would mean it could go in one of 6 directions... or possibly one OR two OR three OR four OR five OR all six directions depending how they would be programmed in. Maybe you can put multiple of them in the same block space as long as it's the same variant of glass?
That would be 64 variants of ONE block - that's including impossible empty block (which you could actually make with debug stick by making all sides be empty - just like with vines or lichen) and that's for every one of the 17 variants of Glass.
All excluding Tinted Glass as they do not have Panes - I assume because of their light blocking properties which makes non-full blocks be tricky to make properly.
Slabs and Stairs were possible just because they could just act like Opaque Slabs and Stairs for light, but Pane would have to be sometimes lit on one side and dark on other all while not being aligned to a single edge of a cubic grid, not even mentioning weird corners... yeah, it would be a mess with Tinted Panes.

Anyway.
Considering all of this. I think this idea is still really cool. Even if we don't mess with transparency on Panes - just having aligned Panes to the Edges of blocks sounds great.
And if it's like Slabs - so thing Panes but located on top and/or bottom edges of Blocks to align with Slabs and Stairs - that could be cool idea too, though slightly more limited.

**Comment by SpiderKolo** [comment]
I should probably mention at the beginning that I'm not the guy who is making the mod.
Telling this now just to avoid confusion.

Sorry if you though I was working on this mod.
