### ISSUE TITLE
[Suggestion] Compatibility with Transluscent Glass mod?

### ISSUE THREAD

**Issue by jamesschool888** [Wurst-Imperium/Mo-Glass#40]
![image_2024-08-13_204057824](https://github.com/user-attachments/assets/864677bd-32bc-4a9f-8f26-93de9aae0013)

please :c

**Comment by Alexander01998** [comment]
Hey @jamesschool888, thanks for the suggestion!

This compatibility issue seems like something that the Translucent Glass mod developer might be able to resolve more cleanly on their side. As far as I can tell, Mo Glass isn't doing anything that would stop Translucent Glass from being compatible, it's just that Translucent Glass's built-in resource pack is currently only changing the vanilla glass textures.

It should a simple fix of making a translucent version the relevant textures in Mo Glass and adding those to the Translucent Glass resource pack. Mo Glass's original textures are located in [this folder](https://github.com/Wurst-Imperium/Mo-Glass/tree/master/src/main/resources/assets/mo_glass/textures/block), including the PSD files, so that should be everything they need to apply the same edits as they did for vanilla glass.

It might be helpful to reach out to the Translucent Glass developer [here](https://github.com/JustinTimeCuber/translucent-glass/issues) and see if they're interested in adding those textures.

Hope this helps!
-Alexander

**Comment by JustinTimeCuber** [comment]
Hey @Alexander01998, I'm the developer of Translucent Glass and I'm seeing this after @jamesschool888 made an issue on my repo. My thoughts are that I can easily include a resource pack to support this on my end, but as you may have seen, Translucent Glass is (slightly) more complex than just a resource pack because I have to move glass blocks to the translucent `RenderLayer`. I'm not sure if there's a way for me to change the render layer for your blocks without adding your mod as a dependency or coming up with some sort of Mixin hacks. I got it working pretty easily with a small patch to your mod, which I can send as a PR. I'll release a corresponding update for the built-in resource pack in my mod if that gets merged.
